package ai.droidlm.intent

object DroidLmActionContract {
    val supportedActions: List<String> = listOf(
        "OPEN_APP",
        "OPEN_APP_STORE_LISTING",
        "OPEN_SETTINGS",
        "TAP_NODE",
        "FOCUS_NODE",
        "TAP",
        "LONG_PRESS",
        "SWIPE",
        "SCROLL",
        "TAP_TEXT",
        "LONG_PRESS_NODE",
        "WAIT_FOR_UI",
        "PRESS_IME_ACTION",
        "DIALOG_ACTION",
        "OPEN_MENU",
        "SELECT_TAB",
        "SET_TOGGLE",
        "EXPAND_COLLAPSE",
        "SET_SLIDER",
        "REFRESH",
        "FIND_TEXT_ON_SCREEN",
        "OPEN_NOTIFICATIONS",
        "OPEN_QUICK_SETTINGS",
        "OPEN_RECENTS",
        "SWITCH_APP",
        "OPEN_URL",
        "OPEN_DEEP_LINK",
        "PICK_FROM_CHOOSER",
        "PICK_FILE",
        "PICK_PHOTO",
        "SHARE_TO_APP",
        "PERMISSION_DECISION",
        "TYPE_TEXT",
        "GLOBAL_BACK",
        "GLOBAL_HOME",
        "TAKE_SCREENSHOT",
        "FOCUS_EDITABLE",
        "SET_SELECTION",
        "INSERT_TEXT",
        "REPLACE_SELECTION",
        "SET_FULL_TEXT",
        "MOVE_CURSOR",
        "TAP_TEXT_ANCHOR",
        "OCR_SCREEN",
        "ANALYZE_SCREENSHOT",
        "INSERT_TEXT_AT_ANCHOR",
        "REPLACE_TEXT_RANGE",
        "APPEND_TEXT",
        "PREPEND_TEXT",
        "SELECT_ALL",
        "DELETE_SELECTED_TEXT",
        "VERIFY_TEXT_CHANGE",
        "FORMAT_CURRENT_LINE_AS_BULLET",
        "REPLACE_CURRENT_DOCUMENT_TEXT",
        "APPEND_DOCUMENT_NOTE",
        "SET_CURRENT_SHEET_CELL",
        "ADD_SPREADSHEET_ROW",
        "ASK_CONFIRMATION",
        "DONE",
        "NO_OP"
    )

    val supportedActionsPrompt: String = supportedActions.joinToString(", ", postfix = ".")

    fun contains(action: String): Boolean = supportedActions.contains(action.uppercase())
}
